### ISSUE TITLE
Function task_time_slice

### ISSUE THREAD

**Issue by Fszta** [w1ne/CANOpenNode-CubeMX-HAL#2]
Hello w1ne,  

First of all thanks for your work. In the main loop of the programm, you call task_time_slice() function. However this is never defined, what is supposed to be the contents of this function ?

Regards, 

Fszta

**Comment by w1ne** [comment]
Hello Fszta,

I have committed fix for the task in main. It was part of production code, task_time_slice() isn't needed for the demo.

Regards,
w1ne
