### ISSUE TITLE
CAN HAL configuration being erased by CO_CANmodule_init function

### ISSUE THREAD

**Issue by julian-poidevin** [w1ne/CANOpenNode-CubeMX-HAL#4]
Hello,

I have a little question regarding CAN peripheral HAL settings being erased by the driver (in [CO_CANmodule_init()](https://github.com/w1ne/CANOpenNode-CubeMX-HAL/blob/90981f9ce582ea52eeea8feeebe6374ac9814f04/Code/Lib/bsp/CANOpenNode/STM32HAL/CO_driver.c#L169) function).

The CAN peripheral is initialized in MX_CAN1_Init() function, see below :
https://github.com/w1ne/CANOpenNode-CubeMX-HAL/blob/90981f9ce582ea52eeea8feeebe6374ac9814f04/Src/can.c#L51-L72

However, it seems the peripheral settings are being re-written in the `CO_CANmodule_init` function, is this normal ?
Shouldn't the following lines be deleted to keep previous HAL settings actives ?
https://github.com/w1ne/CANOpenNode-CubeMX-HAL/blob/90981f9ce582ea52eeea8feeebe6374ac9814f04/Code/Lib/bsp/CANOpenNode/STM32HAL/CO_driver.c#L223-L233

It's not causing problem here as the settings are the same but it caused be some problem because my HAL settings were not the same as you and were being erased by your config.

Thanks a lot.

**Comment by julian-poidevin** [comment]
Hello, just pinging here if someone can provide any additional information. Thanks 😊.

**Comment by w1ne** [comment]
@julian-poidevin I am not providing support for it, as I do not have time for this. If you will find a solution, I can merge it. Of course, the overwriting setting will break the previous config, not sure if it is a problem in this context. You can just comment out `HAL_CAN_Init` and use CO_CANmodule_init only.

Thanks.
